### ISSUE TITLE
Error after an update HA

### ISSUE THREAD

**Issue by titou4307** [Aohzan/hass-prixcarburant#41]
Hello

I have this error since update core assistant : 

```
Enregistreur: homeassistant.config_entries
Source: config_entries.py:551
S'est produit pour la première fois: 20:17:16 (2 occurrences)
Dernier enregistrement: 20:17:32

Error setting up entry Prix Carburant for prix_carburant
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/prix_carburant/__init__.py", line 50, in async_setup_entry
    await tool.init_stations_from_list(
  File "/config/custom_components/prix_carburant/tools.py", line 114, in init_stations_from_list
    response = await self._request_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/prix_carburant/tools.py", line 89, in _request_api
    raise PrixCarburantToolRequestError(
custom_components.prix_carburant.tools.PrixCarburantToolRequestError: API request error 404: {'error_code': 'NotFoundResource', 'message': 'The requested dataset prix-des-carburants-en-france-flux-instantane-v2 does not exist.'}

```

**Comment by mielikki33** [comment]
Hello,

I have the same problem since the update core :)

**Comment by Aohzan** [comment]
Il y a un soucis avec la source des données en effet https://data.economie.gouv.fr/explore/dataset/prix-des-carburants-en-france-flux-instantane-v2/

**Comment by titou4307** [comment]
Bonjour

Ce ne serait pas ce nouveau lien : 

https://data.economie.gouv.fr/explore/dataset/prix-carburants-flux-instantane-v2/table/

ou

https://data.economie.gouv.fr/explore/dataset/prix-carburants-flux-instantane-v2/

**Comment by Aohzan** [comment]
L'URL a l'air de répondre constamment contrairement à l'autre en effet, j'ai update: https://github.com/Aohzan/hass-prixcarburant/releases/tag/3.5.2

**Comment by titou4307** [comment]
Re bonjour
Après mise à jour du moduel depuis HACS, l'intégration refonctionne
@Aohzan 
Merci de la réactivité
