### ISSUE TITLE
Configuration fails after the last update (3.5.3) with HACS

### ISSUE THREAD

**Issue by Idaho947** [Aohzan/hass-prixcarburant#45]
**Describe the bug**
All my sensor are "indisponible" since the last update. The configuration fail.

**Configuration**
From UI

**Expected behavior**
The integration share the price

**Screenshots**
![image](https://github.com/Aohzan/hass-prixcarburant/assets/45599888/37c23a1b-9e18-43ce-9fe0-69a9326c1e28)

![image](https://github.com/Aohzan/hass-prixcarburant/assets/45599888/91251069-a207-4c51-a4a9-84a47cd93533)

**Debug logs**
![image](https://github.com/Aohzan/ipx800v5/assets/2736322/4e2a69a3-db12-4c6d-9aa5-a96aa2e4a2e1)
```
Paste debug logs here

Enregistreur: homeassistant.config_entries
Source: config_entries.py:551
S'est produit pour la première fois: 13:55:13 (3 occurrences)
Dernier enregistrement: 13:56:11

Error setting up entry Prix Carburant for prix_carburant
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/prix_carburant/__init__.py", line 58, in async_setup_entry
    await tool.init_stations_from_location(
  File "/config/custom_components/prix_carburant/tools.py", line 145, in init_stations_from_location
    response_count = await self._request_api(
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/prix_carburant/tools.py", line 89, in _request_api
    raise PrixCarburantToolRequestError(
custom_components.prix_carburant.tools.PrixCarburantToolRequestError: API request error 404: {'error_code': 'NotFoundResource', 'message': 'The requested dataset prix-carburants-flux-instantane-v2 does not exist.'}

**Comment by Aohzan** [comment]
ils ont l'air d'avoir rebasculé sur l'ancienne URL :sob:  (cf https://github.com/Aohzan/hass-prixcarburant/issues/41)

**Comment by Idaho947** [comment]
C'est des champions...

**Comment by Aohzan** [comment]
fixed in https://github.com/Aohzan/hass-prixcarburant/releases/tag/3.5.4
