### ISSUE TITLE
No more data comes up

### ISSUE THREAD

**Issue by TyTroll** [Aohzan/hass-prixcarburant#80]
**Describe the bug**
Hi, 
no more data comes up (I think it's since the HA 2024.11 update)

**Expected behavior**
I tried to uninstall, reinstall, reconfigure but still no feedback

**Screenshots**
![image](https://github.com/user-attachments/assets/02cd4861-c4fa-4c0b-bdba-5153510c2091).

**Debug logs**
```
2024-11-23 00:35:48.726 DEBUG (SyncWorker_5) [custom_components.prix_carburant.tools] Load stations data from local file stations_name.json
2024-11-23 00:35:48.755 INFO (MainThread) [custom_components.prix_carburant] Init stations list near Home-Assistant location
2024-11-23 00:35:48.755 DEBUG (MainThread) [custom_components.prix_carburant.tools] Call https://data.economie.gouv.fr/api/explore/v2.1/catalog/datasets/prix-des-carburants-en-france-flux-instantane-v2/records API to retrieve station data
2024-11-23 00:35:48.781 DEBUG (MainThread) [custom_components.prix_carburant.tools] 41 stations returned by the API
2024-11-23 00:35:48.782 DEBUG (MainThread) [custom_components.prix_carburant.tools] Query stations from 0 to 41/41
2024-11-23 00:35:48.810 INFO (MainThread) [custom_components.prix_carburant] 41 stations found
2024-11-23 00:35:48.810 INFO (MainThread) [custom_components.prix_carburant] Update stations prices
2024-11-23 00:35:48.810 DEBUG (MainThread) [custom_components.prix_carburant.tools] Call https://data.economie.gouv.fr/api/explore/v2.1/catalog/datasets/prix-des-carburants-en-france-flux-instantane-v2/records API to retrieve fuel prices
2024-11-23 00:35:48.810 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56700006: Intermarché
2024-11-23 00:35:48.839 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 29300003: Intermarché MELLAC
2024-11-23 00:35:48.864 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56520005: Relais Guidel Sud
2024-11-23 00:35:48.891 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56310001: Intermarché BUBRY
2024-11-23 00:35:48.918 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56440003: Relais De Languidic
2024-11-23 00:35:48.943 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56670003: Leclerc Riantec
2024-11-23 00:35:48.968 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56700008: Intermarché HENNEBONT
2024-11-23 00:35:48.993 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56700003: Sarl Garage Le Floch
2024-11-23 00:35:49.019 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56520001: Super U GUIDEL
2024-11-23 00:35:49.045 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56100003: Sarl Garage Du Ter
2024-11-23 00:35:49.073 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56520006: Relais De Guidel Nord
2024-11-23 00:35:49.099 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56670001: Intermarché PORT-LOUIS
2024-11-23 00:35:49.123 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56270003: Carrefour Market
2024-11-23 00:35:49.148 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56530001: Dorigal S.A.
2024-11-23 00:35:49.175 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 29300002: Elle-Distribution
2024-11-23 00:35:49.199 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56100008: Intermarché LORIENT C/C LANVEUR
2024-11-23 00:35:49.224 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56700009: Garage Dugor
2024-11-23 00:35:49.250 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56650001: Carrefour Contact
2024-11-23 00:35:49.276 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 29360002: SUPERMARCHE Carrefour Contact
2024-11-23 00:35:49.301 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56607001: Geant Casino
2024-11-23 00:35:49.328 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56700004: Hendis
2024-11-23 00:35:49.353 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56100013: undefined
2024-11-23 00:35:49.377 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56260001: Lardis
2024-11-23 00:35:49.403 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56600002: Sarl Combot
2024-11-23 00:35:49.430 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56700007: Leclerc Express Kervignac
2024-11-23 00:35:49.457 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56850003: undefined
2024-11-23 00:35:49.482 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56109002: undefined
2024-11-23 00:35:49.509 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56850004: undefined
2024-11-23 00:35:49.535 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56270006: Ecomarche
2024-11-23 00:35:49.560 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56600001: Sa Kereol
2024-11-23 00:35:49.586 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56270007: Relais De Lann Bihoue
2024-11-23 00:35:49.613 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56100007: Carrefour Lorient
2024-11-23 00:35:49.639 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56680001: Intermarché PLOUHINEC
2024-11-23 00:35:49.667 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56240004: undefined
2024-11-23 00:35:49.695 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56100009: Intermarché LORIENT Kerfichant
2024-11-23 00:35:49.720 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 29300004: Carrefourmarket
2024-11-23 00:35:49.745 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56690004: Relais De Nostang
2024-11-23 00:35:49.770 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56240003: Carrrefour Market
2024-11-23 00:35:49.796 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56620001: Super U PONT SCORFF
2024-11-23 00:35:49.820 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56100012: Relais Lorient Port
2024-11-23 00:35:49.847 DEBUG (MainThread) [custom_components.prix_carburant.tools] Update fuel prices for station id 56440002: Intermarché LANGUIDIC
2024-11-23 00:35:49.872 DEBUG (MainThread) [custom_components.prix_carburant] Finished fetching prix_carburant data in 1.062 seconds (success: True)
2024-11-23 00:35:49.874 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up prix_carburant platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/prix_carburant/sensor.py", line 90, in async_setup_entry
    PrixCarburant(station_id, station_data, f, data)
  File "/config/custom_components/prix_carburant/sensor.py", line 140, in __init__
    ATTR_CITY: normalize_string(self.station_info[ATTR_CITY]),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/prix_carburant/tools.py", line 408, in normalize_string
    if string.isupper() or string.islower():
       ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'isupper'
```

**Comment by Aohzan** [comment]
Can you test last version please

**Comment by TyTroll** [comment]
The last version 3.8.1-1 work fine, thanks !
